-- MySQL Script generated by MySQL Workbench
-- 10/04/16 14:18:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codeigniterex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codeigniterex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codeigniterex` DEFAULT CHARACTER SET utf8 ;
USE `codeigniterex` ;

-- -----------------------------------------------------
-- Table `codeigniterex`.`systemuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codeigniterex`.`systemuser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `emailaddress` VARCHAR(255) NULL,
  `password` TEXT NULL,
  `salt` VARCHAR(255) NULL,
  `templogin` TINYINT(1) NULL,
  `temppassword` TEXT NULL,
  `tempsalt` VARCHAR(255) NULL,
  `crd` DATETIME NULL,
  `lud` DATETIME NULL,
  `dd` DATETIME NULL,
  `deleted` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
